---
ID: c6be83f3-196c-4967-a366-f1f35f864618
Parent: 8038785a-0203-4db3-aae5-59a93f762792
Template: 854ba861-63ea-4a0c-8c7b-541e9a7ec4c1
Path: /sitecore/system/Settings/Rules/Definitions/Elements/Federated Experience Manager - Page Matching/Tags/Default
BranchID: 9a72c539-dbf8-4dad-96d3-a298fc04add6
SharedFields:
- ID: 42f77151-098f-496a-94cf-590b7edeeabe
  # Tags
  Type: Multilist
  Value: {49110402-7D31-4225-89A4-D4D05393F058}
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T130143Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Standard
- Language: de-DE
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T131012Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Default
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20140403T084943
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
- Language: ja-JP
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T131604Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: デフォルト
