---
ID: a0dd3790-bebc-482c-ad93-eb157f075ae6
Parent: f186dea4-0d8b-44ce-9b70-315de281f9ca
Template: 1db34c92-03b0-4475-9a39-da14e4d9d8fc
Path: /sitecore/content/Applications/Content Editor/Ribbons/Chunks/Feed Presentation/Configure
SharedFields:
- ID: d47ed548-84d5-4622-9886-5cc164727507
  # Icon
  Value: Office/16x16/rss.png
- ID: dbbf9ee3-c30e-4456-a81f-ed8c2e8df91b
  # Click
  Value: item:setfeedpresentation
- ID: dec8d2d5-e3cf-48b6-a653-8e69e2716641
  # __Security
  Value: ar|sitecore\Sitecore Client Authoring|pe|+item:read|pd|+item:read|a?|Everyone|p*|!*|
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T125704Z
    - ID: 4df6da21-e745-444c-956e-1d4a96ab8821
      # Header
      Value: Design
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: a1a31a93-c4a0-4396-b629-67c33001a3cf
      # Tooltip
      Value: Konfigurer en præsentation af elementet i dette feed
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Konfigurer
- Language: de-DE
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T130638Z
    - ID: 4df6da21-e745-444c-956e-1d4a96ab8821
      # Header
      Value: Design
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: a1a31a93-c4a0-4396-b629-67c33001a3cf
      # Tooltip
      Value: Im Feed eine Itempräsentation einrichten
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Konfigurieren
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20090407T065816Z
    - ID: 4df6da21-e745-444c-956e-1d4a96ab8821
      # Header
      Value: Design
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: a1a31a93-c4a0-4396-b629-67c33001a3cf
      # Tooltip
      Value: Set up the design of RSS feed for the selected item.
- Language: ja-JP
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T131319Z
    - ID: 4df6da21-e745-444c-956e-1d4a96ab8821
      # Header
      Value: デザイン
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: a1a31a93-c4a0-4396-b629-67c33001a3cf
      # Tooltip
      Value: このフィードのプレゼンテーション アイテムを設定します
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: 設定
