---
ID: d561ff2b-fdab-4b8a-a6d6-44e0bc8ca064
Parent: 0decfe92-f2ae-4518-83d9-e8279d618fc7
Template: 02404208-46d4-49bf-988b-eb363a52a1c9
Path: /sitecore/content/Applications/WebEdit/Default Placeholder Buttons/Settings
SharedFields:
- ID: 06d5295c-ed2f-4a54-9bf2-26228d113318
  # __Icon
  Value: Office/16x16/window_gear.png
- ID: 1bb289d6-44d7-4fcc-af15-db32b841f957
  # Click
  Value: chrome:placeholder:editSettings
- ID: dec8d2d5-e3cf-48b6-a653-8e69e2716641
  # __Security
  Value: ar|sitecore\Sitecore Client Developing|pe|+item:delete|+item:create|+item:rename|+item:read|+item:write|ar|sitecore\Everyone|pe|!*|
- ID: e8cc41c7-c304-4282-b782-e21ca32d324c
  # Icon
  Value: Office/16x16/window_gear.png
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T125741Z
    - ID: 371e0d96-4f00-4b80-ad14-6284e00493ba
      # Tooltip
      Value: Rediger placeholderindstillingerne.
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Indstillinger
- Language: de-DE
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T130720Z
    - ID: 371e0d96-4f00-4b80-ad14-6284e00493ba
      # Tooltip
      Value: Platzhaltereinstellungen bearbeiten.
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Einstellungen
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20100228T220000Z
    - ID: 371e0d96-4f00-4b80-ad14-6284e00493ba
      # Tooltip
      Value: Edit the placeholder settings.
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
- Language: ja-JP
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T131356Z
    - ID: 371e0d96-4f00-4b80-ad14-6284e00493ba
      # Tooltip
      Value: プレースホルダー設定を編集する
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: 設定
