---
ID: 42ab1b33-d504-4b31-a9ca-e09726d1c7c6
Parent: b5b44327-05b7-4c58-bfae-4087207cdb4f
Template: bdb6fa46-2f76-4bde-8138-52b56c2fc47e
Path: /sitecore/content/Applications/Control Panel/Preferences/Reset My Settings
BranchID: c5f1aa82-f831-477e-ba04-11d435d476e4
SharedFields:
- ID: 20f47b0c-b146-4847-ac4d-0b25983514b3
  # Click
  Value: usermanager:resetmysettings
- ID: ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e
  # __Sortorder
  Value: 200
- ID: dec8d2d5-e3cf-48b6-a653-8e69e2716641
  # __Security
  Value: ar|sitecore\Sitecore Client Authoring|pd|+item:read|pe|+item:read|
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T125605Z
    - ID: 48323b75-9f6a-4779-ac8b-a01da56b35b3
      # Header
      Value: Nulstil mine indstillinger til standardværdier
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Nulstil mine indstillinger
- Language: de-DE
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T130514Z
    - ID: 48323b75-9f6a-4779-ac8b-a01da56b35b3
      # Header
      Value: Meine Einstellungen auf die voreingestellten Werte zurücksetzen
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Meine Einstellungen zurücksetzen
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20070530T144524
    - ID: 48323b75-9f6a-4779-ac8b-a01da56b35b3
      # Header
      Value: Reset to default settings
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
- Language: ja-JP
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T131215Z
    - ID: 48323b75-9f6a-4779-ac8b-a01da56b35b3
      # Header
      Value: 自分の設定をリセットする
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: 自分の設定をリセットする
