---
ID: 5e011392-09e3-4655-b9e5-2441bf80803c
Parent: 7d4f2701-4050-45c9-b175-8feca21da9db
Template: beebc988-14ce-441a-b9e2-2a38d6e4a87d
Path: /sitecore/content/Applications/Portal sidebar/Configurator
SharedFields:
- ID: 0bde2986-e19d-4e02-b998-d4dce9d8ffa5
  # ID
  Value: PortalConfiguratorPortlet
- ID: 3070b56f-9b3c-48b7-8fbd-de8ca6e61179
  # Default
  Value: 1
- ID: 732f96ac-2796-472a-917a-efb209cf535b
  # Order
  Value: 10
- ID: 93e0c773-2747-4391-ab8e-70ec95025419
  # Zone
  Value: DefaultZone
- ID: aed5e3e1-570b-436a-8d8d-4f688e7444ef
  # Control name
  Value: PortalConfiguratorPortlet
- ID: ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e
  # __Sortorder
  Value: 5
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T125622Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Konfigurator
    - ID: d28bee28-9c28-4efa-b649-0a071e0c541c
      # Description
      Value: Viser indstillinger for portalkonfiguration.
- Language: de-DE
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T130535Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Konfigurator
    - ID: d28bee28-9c28-4efa-b649-0a071e0c541c
      # Description
      Value: Zeigt die Portal Konfigurationsoptionen an.
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: d28bee28-9c28-4efa-b649-0a071e0c541c
      # Description
      Value: Shows portal configuration options.
- Language: ja-JP
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T131234Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: コンフィギュレーター
    - ID: d28bee28-9c28-4efa-b649-0a071e0c541c
      # Description
      Value: ポータルの構成オプションを表示します
