---
ID: 7bb7cf57-f605-4914-95be-ae6bff4a3b0c
Parent: 81ed2daf-0d6b-41cb-9392-42964bacd8ff
Template: 8f3d8f9b-2d76-4ace-803f-35415d2b230a
Path: /sitecore/content/Applications/Tools/Installer/Designer/Ribbon/Package/Project
SharedFields:
- ID: ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e
  # __Sortorder
  Value: 0
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T125640Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Projekt
    - ID: c95d21bd-66c3-444b-a37f-d346cbaf2b55
      # Header
      Value: Projekt
- Language: de-DE
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T130601Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Projekt
    - ID: c95d21bd-66c3-444b-a37f-d346cbaf2b55
      # Header
      Value: Projekt
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20060517T151917
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\Admin
    - ID: c8f93afe-bfd4-4e8f-9c61-152559854661
      # __Valid from
      Value: 20060320T112014
    - ID: c95d21bd-66c3-444b-a37f-d346cbaf2b55
      # Header
      Value: Project
- Language: ja-JP
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T131254Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: プロジェクト
    - ID: c95d21bd-66c3-444b-a37f-d346cbaf2b55
      # Header
      Value: プロジェクト
