---
ID: 0eed4460-01eb-4eed-8cc5-e8f003daab9f
Parent: cd4c8a03-bdd5-497a-9530-791e8ee07a3c
Template: 8f3d8f9b-2d76-4ace-803f-35415d2b230a
Path: /sitecore/content/Applications/Templates/Template Builder/Ribbon/Options/Configure
SharedFields:
- ID: 8bb9a5e3-cae8-49c6-b830-258a51d970c9
  # ID
  Value: BuilderConfigureChunk
- ID: ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e
  # __Sortorder
  Value: 300
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T125526Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Konfigurer
    - ID: c95d21bd-66c3-444b-a37f-d346cbaf2b55
      # Header
      Value: Skabelon
- Language: de-DE
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T130429Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Konfigurieren
    - ID: c95d21bd-66c3-444b-a37f-d346cbaf2b55
      # Header
      Value: Template
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20060725T150832
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\Admin
    - ID: c8f93afe-bfd4-4e8f-9c61-152559854661
      # __Valid from
      Value: 20060316T145941
    - ID: c95d21bd-66c3-444b-a37f-d346cbaf2b55
      # Header
      Value: Template
- Language: ja-JP
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T131139Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: 設定
    - ID: c95d21bd-66c3-444b-a37f-d346cbaf2b55
      # Header
      Value: テンプレート
