---
ID: 81ed2daf-0d6b-41cb-9392-42964bacd8ff
Parent: 520a5036-20f5-4e83-b6d3-c46b14c23039
Template: ec6d62a5-5d00-4329-8958-8ac1ad100ebb
Path: /sitecore/content/Applications/Tools/Installer/Designer/Ribbon/Package
SharedFields:
- ID: 12c1ceb4-f549-472a-97ed-99bff70eb84e
  # ID
  Value: Package
- ID: ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e
  # __Sortorder
  Value: 100
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T125644Z
    - ID: 5453dc07-6a17-48ba-8d05-17db90a2e795
      # Header
      Value: Pakke
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Pakke
- Language: de-DE
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T130606Z
    - ID: 5453dc07-6a17-48ba-8d05-17db90a2e795
      # Header
      Value: Paket
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Paket
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20060517T151917
    - ID: 5453dc07-6a17-48ba-8d05-17db90a2e795
      # Header
      Value: Package
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\Admin
    - ID: c8f93afe-bfd4-4e8f-9c61-152559854661
      # __Valid from
      Value: 20060320T111959
- Language: ja-JP
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T131259Z
    - ID: 5453dc07-6a17-48ba-8d05-17db90a2e795
      # Header
      Value: パッケージ
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: パッケージ
