---
ID: 2d72683d-31ab-4071-833b-2712c196f91c
Parent: 63fd69ef-4448-4f6b-abed-e8abf4844ce3
Template: ec6d62a5-5d00-4329-8958-8ac1ad100ebb
Path: /sitecore/content/Applications/Tools/Installer/Preview/Ribbon/Package
SharedFields:
- ID: 12c1ceb4-f549-472a-97ed-99bff70eb84e
  # ID
  Value: PackageStrip
- ID: ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e
  # __Sortorder
  Value: 100
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T125552Z
    - ID: 5453dc07-6a17-48ba-8d05-17db90a2e795
      # Header
      Value: Pakke
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Pakke
- Language: de-DE
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T130457Z
    - ID: 5453dc07-6a17-48ba-8d05-17db90a2e795
      # Header
      Value: Paket
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Paket
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20060620T153621
    - ID: 5453dc07-6a17-48ba-8d05-17db90a2e795
      # Header
      Value: Package
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\Admin
    - ID: c8f93afe-bfd4-4e8f-9c61-152559854661
      # __Valid from
      Value: 20060320T111959
- Language: ja-JP
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T131200Z
    - ID: 5453dc07-6a17-48ba-8d05-17db90a2e795
      # Header
      Value: パッケージ
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: パッケージ
