---
ID: 4062dff9-69e4-4ae6-97b3-bdb4bcde5604
Parent: 425f7a64-8f77-4a64-9b22-3b271b2e523c
Template: b40ee369-172f-4a95-bcf5-2a740dea8f06
Path: /sitecore/content/Applications/Layouts/IDE/Toolbar/Security
BranchID: 09b0eb6b-b6b6-4e40-8804-137a4cc14074
SharedFields:
- ID: 1172f251-dad4-4efb-a329-0c63500e4f1e
  # __Masters
  Type: tree list
  Value: |
    {09B0EB6B-B6B6-4E40-8804-137A4CC14074}
    {52DECC09-A36C-465A-B532-4186ADA9C731}
- ID: ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e
  # __Sortorder
  Value: 100
- ID: dec8d2d5-e3cf-48b6-a653-8e69e2716641
  # __Security
  Value: ar|sitecore\Sitecore Client Account Managing|pe|+item:read|pd|+item:read|ar|sitecore\Sitecore Client Securing|pe|+item:read|pd|+item:read|ar|sitecore\Sitecore Client Users|pe|!*|
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T125603Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: 72a56da7-0f41-4789-b585-473206d4d407
      # Header
      Value: Sikkerhed
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Sikkerhed
- Language: de-DE
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T130512Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: 72a56da7-0f41-4789-b585-473206d4d407
      # Header
      Value: Sicherheit
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Sicherheit
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20051116T141753
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\Admin
    - ID: 72a56da7-0f41-4789-b585-473206d4d407
      # Header
      Value: Security
    - ID: c8f93afe-bfd4-4e8f-9c61-152559854661
      # __Valid from
      Value: 20051116T141753
- Language: ja-JP
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T131213Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: 72a56da7-0f41-4789-b585-473206d4d407
      # Header
      Value: セキュリティ
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: セキュリティ
