---
ID: 3881e0e9-b930-4850-9954-3ea17c7a7905
Parent: 57581ca8-d857-4527-998b-c6c6332747dd
Template: 3b4fde65-16a8-491d-bf15-99ce83cf3506
Path: /sitecore/system/Marketing Control Panel/Taxonomies/Channel/Online/Automation programs/Email automation
SharedFields:
- ID: 8fb875eb-3ad3-44ff-87e1-998370cc3199
  # Code
  Value: 01
- ID: a4f985d9-98b3-4b52-aaaf-4344f6e747c6
  # __Workflow
  Value: 
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T130106Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: 8bdee96a-e8f5-446a-a1d2-568c3018c98e
      # Image
      Value: "<image mediaid=\"{903E4C67-D2D2-4BF4-B231-CB63D792EA34}\" />"
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Mailautomatisering
- Language: de-DE
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T130936Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: 8bdee96a-e8f5-446a-a1d2-568c3018c98e
      # Image
      Value: "<image mediaid=\"{903E4C67-D2D2-4BF4-B231-CB63D792EA34}\" />"
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Email Automation
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20141115T110528Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: 8bdee96a-e8f5-446a-a1d2-568c3018c98e
      # Image
      Value: "<image mediaid=\"{903E4C67-D2D2-4BF4-B231-CB63D792EA34}\" />"
- Language: ja-JP
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T131531Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: 8bdee96a-e8f5-446a-a1d2-568c3018c98e
      # Image
      Value: "<image mediaid=\"{903E4C67-D2D2-4BF4-B231-CB63D792EA34}\" />"
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: 電子メール オートメーション
