---
ID: 609599b2-95cd-4aa6-a121-7c3f71aad94d
Parent: 7a22ec7c-aaca-4ad5-8ab9-a83c1e8c68e8
Template: f8a17d6a-118e-4cd7-b5f5-88ff37a4f237
Path: /sitecore/system/Field types/System Types/Security
SharedFields:
- ID: 06d5295c-ed2f-4a54-9bf2-26228d113318
  # __Icon
  Value: Network/16x16/lock.png
- ID: 0f0a5388-0467-4a45-95c0-729b1d6db9fd
  # Control
  Value: content:Security
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T125623Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Sikkerhed
- Language: de-DE
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T130537Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Sicherheit
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20070416T123658
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
- Language: ja-JP
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20170407T131236Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: Security
